version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: battery_backend
    restart: unless-stopped
    ports:
      - "8036:8036"
    environment:
      - DB_HOST=mysql_db
      - DB_USER=root
      - DB_PASSWORD=your_strong_password
      - DB_NAME=battery_erp
      - JWT_SECRET=your_jwt_secret_key
      - SEED_DATABASE=true
    depends_on:
      - mysql_db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: battery_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  mysql_db:
    image: mysql:8.0
    container_name: battery_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: your_strong_password
      MYSQL_DATABASE: battery_erp
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: